### ISSUE TITLE
install?

### ISSUE THREAD

**Issue by gangofnuns** [AndreZiviani/aws-fuzzy#33]
This is probably obvious to go developers, but how does one install these? 
Looks like a wonderfully interesting tool.

**Comment by AndreZiviani** [comment]
Just download the binary for your platform/architecture from the releases page, no installation or anything else required

I’m compiling for the most popular platform/architectures but only Linux x86 is tested

**Comment by gangofnuns** [comment]
Hello Andre --

The Linux version runs very well inside a Linux container.  Many thanks!
This is a wonderful app!

RE: Cross-Compiles

I also tried running the Darwin release on my Mac, but failed to get things
working
on my first attempt.

BACKGROUND:
-- I've gone through the necessary app whitelisting with spctl.
-- I've gone through Apple's obligatory code signing process.
-- I am running on Intel hardware, under Big Sur -- not M1.

It seems like the Darwin executable may not be working just yet.
I'm leaning toward this conclusion because a.) It segfaults immediately
on execution, and b.) diagnostic tools show it does not have the typical
MacOS App structure:

MacBook-Pro:tmp $ codesign -d -v -v aws-fuzzy-all-0.11.0
Executable=/Users/marc/local/bin/tmp/aws-fuzzy-all-0.11.0
Identifier=aws-fuzzy-all-0
Format=Mach-O thin (x86_64)
CodeDirectory v=20400 size=65992 flags=0x0(none) hashes=2057+2
location=embedded
Signature size=2040
Authority=aws-fuzzy-internal
Signed Time=Jan 29, 2022 at 7:17:48 AM
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=92

I might try recompiling this, as it would be nice to have
a working native version for my mac.

**Comment by AndreZiviani** [comment]
Hi @gangofnuns, I've made some improvements on error checking/handling and quickly tested it on Intel MacOS Catalina please check [this release](https://github.com/AndreZiviani/aws-fuzzy/releases/tag/v0.11.0-rc3).

I'm planning on rearchitecting the code to improve error handling and error messages but I can't give an ETA on that, if you have problems with this new release please let me know and I will try to find a Mac with a more recent version

**Comment by gangofnuns** [comment]
Hey AndreZiviani --

Thank you for the note!   I tried the new release -- but it still fails.
Codesign reports that it has no 'plist.info' file, which is the essential
key-value information needed for a MacOS App.  I'm think you may
need to create that file in the distro, but I haven't read through the
details yet.

Again, many thanks for the software -- Linux version works quite well !

Cheers --

MacBook-Pro:tmp$ codesign -d -v -v aws-fuzzy_0.11.0-rc3_darwin_amd64
Executable=/Users/marc/local/bin/tmp/aws-fuzzy_0.11.0-rc3_darwin_amd64
Identifier=aws-fuzzy_0.11.0-rc3_darwin_amd64
Format=Mach-O thin (x86_64)
CodeDirectory v=20400 size=66810 flags=0x0(none) hashes=2082+2
location=embedded
Signature size=2040
Authority=aws-fuzzy-internal
Signed Time=Jan 30, 2022 at 10:49:38 AM
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=112

**Comment by AndreZiviani** [comment]
What happens when you run it? It is indeed not signed, I don’t have an apple developer account

**Comment by gangofnuns** [comment]
Hey Andre --

On MacOS Big Sur, using non-Apple hardware (e.g. Intel i7, no M1 chip), you
can
mark a downloaded program as runnable using the 'spctl' utility.  I have
done this,
and tested the procedure on several compiled binaries of my own.

In addition to marking the app as 'runnable' and 'trusted' by the local OS,
you must sign the compiled app using a self-signed certificate, and a
signing
process, which is managed by Apple's "codesign" utility.   I have performed
this process many times.

In the case of aws-fuzzy, the process is killed immediately with a segfault
11
when run from the command line.

Hope that helps!   Cheers --

**Comment by AndreZiviani** [comment]
Hi Marc
I will try to test it on Big Sur, in the meantime can you try renaming your `~/.aws` dir to something else and try running it again? just to make sure its not something related to your config

**Comment by AndreZiviani** [comment]
@gangofnuns I found the issue, CI was building using an old Golang version, this new release should hopefully work 
https://github.com/AndreZiviani/aws-fuzzy/releases/tag/v0.11.0-rc4

**Comment by AndreZiviani** [comment]
Hi @gangofnuns, did it work?

**Comment by gangofnuns** [comment]
Alas, no:  Same results.

(i)[---->]~/local/bin2ools/bin2alpha/fuzz$ codesign -d -v -v
aws-fuzzy_0.11.0-rc4_darwin_amd64
Executable=/Users/marc/local/bin2ools/bin2alpha/fuzz/aws-fuzzy_0.11.0-rc4_darwin_amd64
Identifier=aws-fuzzy_0.11.0-rc4_darwin_amd64
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=33842 flags=0x0(none) hashes=1053+2
location=embedded
Signature size=2040
Authority=aws-fuzzy-internal
Signed Time=Feb 11, 2022 at 1:32:40 PM
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=112

**Comment by AndreZiviani** [comment]
Hey @gangofnuns looks like the issue was with the software I used to compress the binary (UPX), this new release was made without it hopefully it will finally work
https://github.com/AndreZiviani/aws-fuzzy/releases/tag/v0.12.0-rc1

**Comment by gangofnuns** [comment]
Hey AndreZiviani -- 

The binary does indeed run now.   However, there's a problem when running either config or chart where it throws errors, complaining it wasn't build with the 'cdo' library, and thus cannot load a critical dependency:  sqlite3.      Progress, however.     Best of luck!

**Comment by AndreZiviani** [comment]
Hi @gangofnuns 

I was using sqlite to cache some results but there isn't a simple way to cross compile it so I dropped it to use a simpler approach:
https://github.com/AndreZiviani/aws-fuzzy/releases/tag/v0.12.0-rc2

**Comment by gangofnuns** [comment]
Hey AndreZiviani --

Thanks for the response!   Looks like the latest 0.12.0-rc2 gives a
backtrace, e.g. when I run with "config rds" as arguments.

(i)[---->]~/local/bintools/test$ ./aws-fuzzy_0.12.0-rc2_darwin_amd64 config
rds
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/AndreZiviani/aws-fuzzy/internal/config.Config({0x16df5a0,
0xc0002e09c0}, 0xc000037800, {0x16071c9, 0x1})
/home/runner/work/aws-fuzzy/aws-fuzzy/internal/config/config.go:112 +0x9e8
github.com/AndreZiviani/aws-fuzzy/internal/config.wrapper(0xc000037800,
{0x100ab74, 0x15808c0, 0x1560080}, {0x16071c9, 0x1})
/home/runner/work/aws-fuzzy/aws-fuzzy/internal/config/config.go:140 +0x1b3
github.com/AndreZiviani/aws-fuzzy/internal/config.(*ConfigCommand).Execute(0xc0001ffe80,
{0xc000075900, 0xc000037800, 0x20})
/home/runner/work/aws-fuzzy/aws-fuzzy/internal/config/config.go:160 +0x2b
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00024c380,
{0xc00001e1c0, 0x3, 0x2})
***@***.***/parser.go:335
+0x94e
github.com/jessevdk/go-flags.(*Parser).Parse(...)
***@***.***/parser.go:191
github.com/AndreZiviani/aws-fuzzy/internal/cli.Run()
/home/runner/work/aws-fuzzy/aws-fuzzy/internal/cli/main.go:20 +0xc5
main.main()
/home/runner/work/aws-fuzzy/aws-fuzzy/cmd/aws-fuzzy/main.go:8 +0x17

Cheers --

**Comment by AndreZiviani** [comment]
that bug occurred only on the first run so I didn't give much attention but after removing sqlite it happens every time, sorry for all this back and forth, thanks for your patience and testing

https://github.com/AndreZiviani/aws-fuzzy/releases/tag/v0.12.0-rc3

**Comment by gangofnuns** [comment]
Hey AndreZiviani -- 

Definitely getting closer!   Now, when I run the app, it seems to try to do something , but still fails a bit.  I'm not completely sure it's a problem with your software -- but it seems to be repeatedly trying and failing to log into sso, even after it is configured on my end.   I have other credentials I can put into the environment, but they do not seem to work either.   Here is the output: 


~/local/bintools/test$ ./aws-fuzzy_0.12.0-rc3_darwin_amd64 sso login -p arch
failed to get role credentials, the SSO session has expired or is invalid
failed to get role credentials, the SSO session has expired or is invalid
failed to get role credentials, the SSO session has expired or is invalid
failed to get role credentials, the SSO session has expired or is invalid
[...]

Produces  a few hundred lines like the above then seems to get caught 
in a loop.  Sending a sig QUIT stops the process.

**Comment by AndreZiviani** [comment]
hi @gangofnuns thats something that happens even with official aws cli, try removing your SSO cache:
`rm ~/.aws/sso/cache/*.json`

and log again:
`aws-fuzzy sso login`

**Comment by rowbot1** [comment]
I get an error
profile default not found!
I ran the command ./aws-fuzzy_0.12._linux_amd64 config ec2
Thanks

**Comment by AndreZiviani** [comment]
Hi @rowbot1 
Either set `AWS_PROFILE` environment variable or use the `-p <profile name>` flag

**Comment by rowbot1** [comment]
I did this but get the same error

**Comment by rowbot1** [comment]
in .aws/credentials
[default]
aws_access_key_id=xxxx
aws_secrect_access_key=xxx
aws_session_token=xx

command 
./aws-fuzzy_0.12.0_linux_amd64 config ec2 -p default

**Comment by AndreZiviani** [comment]
I've never tested it with static credentials, only with SSO, will try it later

**Comment by rowbot1** [comment]
thank you

**Comment by AndreZiviani** [comment]
@rowbot1 whats in your `~/.aws/config`?

**Comment by gangofnuns** [comment]
Hey, just fyi, I was able to get SSO to authenticate, but never IAM.   It
could be I was just using the wrong combinations of flags.  The tool seems
prodigious but documentation was a bit harder to come by.  Love it though.
Willing to try again.

**Comment by AndreZiviani** [comment]
> Hey, just fyi, I was able to get SSO to authenticate, but never IAM.   It could be I was just using the wrong combinations of flags.

Can you post your (redacted) `~/.aws/config`? 
I did some tests yesterday but I could not use plain IAM credentials I had to use it with MFA, turn out that AWS SDK does not implement an automatic flow when using MFA without assume role so I made some changes to support it (can crease a new release if you want to try it)

> The tool seems prodigious but documentation was a bit harder to come by.  Love it though.

Thanks a lot! I agree that the documentation is lacking... I've just switched jobs and we are not using SSO yet so I will improve on IAM authentication, documentation and (hopefully) features.

**Comment by AndreZiviani** [comment]
I will post my config if you want to compare

```
$ cat ~/.aws/config
[profile dev]
region = us-east-1

$ cat ~/.aws/credentials
[dev]
aws_access_key_id = AKIA[...]
aws_secret_access_key = [...]
mfa_serial = arn:aws:iam::123456789012:mfa/[...]
```

**Comment by rowbot1** [comment]
cat ~/.aws/config 
[default]
region = eu-west-3
output = json
cli_history = enabled
